export enum HeadersTable {
  name = 'Nombre',
  id = 'Id',
  description = 'Descripcion',
  selection = 'Seleccion',
  level = 'Nivel',
  image = 'Imagen',
  x_brand_code = 'PROYECTO',
  x_state = 'ESTADO',
  serie = 'SERIE',
  salesOrder = 'PEDIDO',
  x_name_0 = 'CLIENTE',
  x_name = 'PRODUCTO',
  x_product_qty = 'CANTIDAD',
  formularios = 'FORMULARIOS',
  project = 'PROYECTO',
  customer = 'CLIENTE',
  status = 'ESTADO',
  startDate = 'FECHA INICIO',
  serialNumber = 'Nº DE SERIE',
  checkpointId = 'ID',
  selects = 'Selección',
  example = 'Ejemplo',
  descriptionHeader = 'Descripción',
  value = 'Valor',
}
