/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormFields { 
    id?: boolean;
    status?: boolean;
    section?: boolean;
    type?: boolean;
    project?: boolean;
    personInCharge?: boolean;
    customer?: boolean;
    salesOrder?: boolean;
    item?: boolean;
    serialNumber?: boolean;
    startDate?: boolean;
    signature?: boolean;
    endDate?: boolean;
    blocks?: boolean;
    xBveFormulariosId?: boolean;
}

