/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormInputOptionalXBveFormulariosIdExcludingId } from './formInputOptionalXBveFormulariosIdExcludingId';
import { S3FileOptionalXBveFormulariosIdExcludingId } from './s3FileOptionalXBveFormulariosIdExcludingId';


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<FormBlock, \'id\'>, \'xBveFormulariosId\'>, schemaOptions: { exclude: [ \'id\' ], optional: [ \'xBveFormulariosId\' ] })
 */
export interface FormBlockOptionalXBveFormulariosIdExcludingId { 
    name?: string;
    blockNumber?: number;
    user?: string;
    status?: string;
    date?: string;
    language?: Array<object>;
    inputs?: Array<FormInputOptionalXBveFormulariosIdExcludingId>;
    imagenes?: Array<S3FileOptionalXBveFormulariosIdExcludingId>;
}

