/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormInput } from './formInput';
import { S3File } from './s3File';


export interface FormBlock { 
    id?: string;
    name?: string;
    blockNumber?: number;
    user?: string;
    status?: string;
    date?: string;
    language?: Array<object>;
    inputs?: Array<FormInput>;
    imagenes?: Array<S3File>;
}

