/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: MasterFormInputWithRelations, schemaOptions: { includeRelations: true })
 */
export interface MasterFormInputWithRelations { 
    checkpointId?: string;
    name: string;
    description: string;
    level: string;
    selects?: Array<string>;
    language?: Array<object>;
}

