/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MasterFormBlockWithRelations } from './masterFormBlockWithRelations';


/**
 * (tsType: MasterFormWithRelations, schemaOptions: { includeRelations: true })
 */
export interface MasterFormWithRelations { 
    id?: string;
    name: string;
    section: string;
    type: string;
    formato?: string;
    edicion?: string;
    blocks?: Array<MasterFormBlockWithRelations>;
}

