/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<CustomData, \'id\'>, schemaOptions: { title: \'NewCustomData\', exclude: [ \'id\' ] })
 */
export interface NewCustomData { 
    key: string;
    values: Array<string>;
}

