/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormBlockExcludingId } from './formBlockExcludingId';


/**
 * (tsType: Omit<Form, \'id\'>, schemaOptions: { title: \'NewForm\', exclude: [ \'id\' ] })
 */
export interface NewForm { 
    status: string;
    section: string;
    type: string;
    project: string;
    personInCharge: string;
    customer: string;
    salesOrder?: string;
    item: string;
    serialNumber: string;
    startDate: string;
    signature?: string;
    endDate?: string;
    blocks?: Array<FormBlockExcludingId>;
    xBveFormulariosId?: string;
}

