/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<XBveFormularios, \'id\'>, schemaOptions: { title: \'NewXBveFormularios\', exclude: [ \'id\' ] })
 */
export interface NewXBveFormularios { 
    x_name_4?: string;
    x_origin?: string;
    x_product_id?: number;
    x_date_planned_start?: string;
    x_product_qty?: number;
    x_state?: string;
    x_date_start?: string;
    x_procurement_group_id?: number;
    x_sale_id?: number;
    x_product_id_0?: number;
    x_product_tmpl_id?: number;
    x_sale_id_0?: number;
    x_team_id?: number;
    x_partner_id?: number;
    x_client_order_ref?: string;
    x_name_1?: string;
    x_client_ref?: string;
    x_user_id?: number;
    x_analytic_account_id?: number;
    x_analytic_account_id_0?: number;
    x_code?: string;
    x_brand_code?: string;
    x_partner_id_0?: number;
    x_name_0?: string;
    x_user_id_0?: number;
    x_login?: string;
    x_product_tmpl_id_0?: number;
    x_brand_id?: number;
    x_name?: string;
    x_categ_id?: number;
    x_partner_id_1?: number;
    x_name_2?: string;
}

