/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<S3File, \'id\'>, schemaOptions: { exclude: [ \'id\' ] })
 */
export interface S3FileExcludingId { 
    fileName: string;
    file: string;
    mime: string;
    size: number;
    bucket: string;
    createdAt: string;
    updatedAt: string;
}

