/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<XBveEmpleados>, schemaOptions: { partial: true })
 */
export interface XBveEmpleadosPartial { 
    id?: number;
    x_pin?: string;
    x_name?: string;
    x_department_id?: number;
    x_active?: boolean;
    x_job_id?: number;
    x_barcode?: string;
}

