/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface XBveFormulariosFields { 
    id?: boolean;
    x_name_4?: boolean;
    x_origin?: boolean;
    x_product_id?: boolean;
    x_date_planned_start?: boolean;
    x_product_qty?: boolean;
    x_state?: boolean;
    x_date_start?: boolean;
    x_procurement_group_id?: boolean;
    x_sale_id?: boolean;
    x_product_id_0?: boolean;
    x_product_tmpl_id?: boolean;
    x_sale_id_0?: boolean;
    x_team_id?: boolean;
    x_partner_id?: boolean;
    x_client_order_ref?: boolean;
    x_name_1?: boolean;
    x_client_ref?: boolean;
    x_user_id?: boolean;
    x_analytic_account_id?: boolean;
    x_analytic_account_id_0?: boolean;
    x_code?: boolean;
    x_brand_code?: boolean;
    x_partner_id_0?: boolean;
    x_name_0?: boolean;
    x_user_id_0?: boolean;
    x_login?: boolean;
    x_product_tmpl_id_0?: boolean;
    x_brand_id?: boolean;
    x_name?: boolean;
    x_categ_id?: boolean;
    x_partner_id_1?: boolean;
    x_name_2?: boolean;
}

