/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface XBveEmpleadosFields { 
    id?: boolean;
    x_pin?: boolean;
    x_name?: boolean;
    x_department_id?: boolean;
    x_active?: boolean;
    x_job_id?: boolean;
    x_barcode?: boolean;
}

