/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XBveFormulariosScopeFilter } from './xBveFormulariosScopeFilter';


export interface XBveFormulariosIncludeFilterItems { 
    relation?: string;
    scope?: XBveFormulariosScopeFilter;
}

