/**
 * bsi-qf-backend
 * Formularios de Inspección de Calidad BSI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XBveFormulariosFields } from './xBveFormulariosFields';
import { XBveFormulariosIncludeFilterItems } from './xBveFormulariosIncludeFilterItems';


export interface XBveFormulariosFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string>;
    fields?: XBveFormulariosFields;
    include?: Array<XBveFormulariosIncludeFilterItems>;
}

